# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-31 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0022_service_last_check_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestevent',
            name='user_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requestevent',
            name='user_identifier',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='client_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
