# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-06 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0023_user_analytics'),
    ]

    operations = [
        migrations.RenameModel('OWSService', 'EventType'),
        migrations.RenameField(
            model_name='notificationmetricdefinition',
            old_name='use_ows_service',
            new_name='use_event_type',
        ),
        migrations.RenameField(
            model_name='metricnotificationcheck',
            old_name='ows_service',
            new_name='event_type',
        ),
        migrations.RenameField(
            model_name='requestevent',
            old_name='ows_service',
            new_name='event_type',
        ),
        migrations.AlterField(
            model_name='requestevent',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='metricvalue',
            old_name='ows_service',
            new_name='event_type',
        ),
        migrations.AlterUniqueTogether(
            name='metricvalue',
            unique_together=set([('valid_from', 'valid_to', 'service', 'service_metric', 'resource', 'label', 'event_type')]),
        ),
    ]
