# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-10 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_profile_recommendation'),
        ('people', '0027_auto_20180414_2120'),
    ]

    operations = [
    ]
