# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-07 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0029_merge_20180510_1701'),
        ('people', '0028_auto_20180606_1543'),
    ]

    operations = [
    ]
