# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-10 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_merge'),
        ('base', '0033_auto_20180330_0951'),
    ]

    operations = [
    ]
