# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_resourcebase_dirty_state'),
        ('base', '0038_merge_20180607_1508'),
    ]

    operations = [
    ]
