# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-02 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qgis_server', '0005_auto_20170823_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qgisserverlayer',
            name='default_style',
        ),
        migrations.RemoveField(
            model_name='qgisserverlayer',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='qgisserverlayer',
            name='styles',
        ),
        migrations.RemoveField(
            model_name='qgisservermap',
            name='map',
        ),
        migrations.DeleteModel(
            name='QGISServerLayer',
        ),
        migrations.DeleteModel(
            name='QGISServerMap',
        ),
    ]
